version: "3.7"

services:
  hsm-playground:
    container_name: hsm-playground
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SUBCOMMAND=${SUBCOMMAND}
        - MODULE_LOCATION=${MODULE_LOCATION}
        - TOKEN_PIN=${TOKEN_PIN}
        - KEY_LABEL=${KEY_LABEL}
        - MESSAGE=${MESSAGE}
        - SIGNATURE=${SIGNATURE}
        - CERTIFICATE_PATH=${CERTIFICATE_PATH}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    devices:
       - /dev/k7pf0
